config/routes.rb
Mailer::Application.routes.draw do
  resources :forgotusers

  resources :loginusers

  resources :mails

  resources :users

  get '/signup' => 'users#new'
  get '/compose' =>'mails#new'
  get '/login' => 'loginusers#new', as: 'login'
  get '/forgotpassword' => 'forgotusers#new'
  match "/loginusers/new" => redirect("login")

    root :to => 'loginusers#new'

end

app/models/loginuser.rb
class Loginuser < ActiveRecord::Base
  attr_accessible :emailId, :password, :user_id
  has_one :user
end

app/controllers/loginusers_controller.rb
class LoginusersController < ApplicationController
  # GET /loginusers
  # GET /loginusers.json
  def index
    @loginusers = Loginuser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @loginusers }
    end
  end

  # GET /loginusers/1
  # GET /loginusers/1.json
  def show
    @loginuser = Loginuser.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @loginuser }
      @mailid = @loginuser.emailId
    @user = User.where(emailId: @mailid)[0]
    if(@user!=nil && @user.password == @loginuser.password)
      session[:mailid] = @mailid
      session[:type]="Inbox"
      @loginuser.destroy
      redirect_to(mails_path) and return
    else
      @loginuser.destroy
      redirect_to(login_path, :notice => "Invalid Login Credentials") and return
    end
    end
  end

  # GET /loginusers/new
  # GET /loginusers/new.json
  def new
    if(params["session"] == 'nil')
      session[:mailid] = nil
    end
    @loginuser = Loginuser.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @loginuser }
    end
    
  end

  # GET /loginusers/1/edit
  def edit
    @loginuser = Loginuser.find(params[:id])
  end

  # POST /loginusers
  # POST /loginusers.json
  def create
    @loginuser = Loginuser.new(params[:loginuser])

    respond_to do |format|
      if @loginuser.save
        format.html { redirect_to @loginuser, notice: 'Loginuser was successfully created.' }
        format.json { render json: @loginuser, status: :created, location: @loginuser }
      else
        format.html { render action: "new" }
        format.json { render json: @loginuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /loginusers/1
  # PUT /loginusers/1.json
  def update
    @loginuser = Loginuser.find(params[:id])

    respond_to do |format|
      if @loginuser.update_attributes(params[:loginuser])
        format.html { redirect_to @loginuser, notice: 'Loginuser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @loginuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loginusers/1
  # DELETE /loginusers/1.json
  def destroy
    @loginuser = Loginuser.find(params[:id])
    @loginuser.destroy

    respond_to do |format|
      format.html { redirect_to loginusers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/loginusers_helper.rb
module LoginusersHelper
end

app/views/loginusers/_form.html.erb
  <div class="transbox">
  <%= form_for @loginuser , :html => { :class => "loginform" } do |f| %>
  <% if @loginuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loginuser.errors.count, "error") %> prohibited this loginuser from being saved:</h2>

      <ul>
      <% @loginuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% session[:showText] = 'false' %>
  <div class="field">
    <%= f.label :'Email Id' %><br />
    <%= f.text_field :emailId %>
  </div>
  <div class="field">
    <%= f.label :Password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit :Login %>
  </div>
  <input type = "button" value="Forgot Password" onclick="forgot()">
<% end %>
<script type="text/javascript">
function forgot()
{
  var a = document.getElementById('loginuser_emailId').value
  window.location = "forgotpassword?mailid="+a
}
</script>
</div>

app/views/loginusers/edit.html.erb
<h1>Editing loginuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @loginuser %> |
<%= link_to 'Back', loginusers_path %>

app/views/loginusers/index.html.erb
<h1>Listing loginusers</h1>

<table>
  <tr>
    <th>Emailid</th>
    <th>Password</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @loginusers.each do |loginuser| %>
  <tr>
    <td><%= loginuser.emailId %></td>
    <td><%= loginuser.password %></td>
    <td><%= loginuser.user_id %></td>
    <td><%= link_to 'Show', loginuser %></td>
    <td><%= link_to 'Edit', edit_loginuser_path(loginuser) %></td>
    <td><%= link_to 'Destroy', loginuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<!--<%= link_to 'New Loginuser', new_loginuser_path %>-->

app/views/loginusers/new.html.erb
<%= link_to 'Signup', new_user_path %>
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', loginusers_path %>

app/views/loginusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Emailid:</b>
  <%= @loginuser.emailId %>
</p>

<p>
  <b>Password:</b>
  <%= @loginuser.password %>
</p>

<p>
  <b>User:</b>
  <%= @loginuser.user_id %>
</p>


<%= link_to 'Edit', edit_loginuser_path(@loginuser) %> |
<%= link_to 'Back', loginusers_path %>