config/routes.rb
Mailer::Application.routes.draw do
  resources :forgotusers

  resources :loginusers

  resources :mails

  resources :users

  get '/signup' => 'users#new'
  get '/compose' =>'mails#new'
  get '/login' => 'loginusers#new', as: 'login'
  get '/forgotpassword' => 'forgotusers#new'
  match "/loginusers/new" => redirect("login")

    root :to => 'loginusers#new'

end

app/models/forgotuser.rb
class Forgotuser < ActiveRecord::Base
  attr_accessible :newPassword, :securityAnswer, :securityQuestion
  has_one :user
end

app/controllers/forgotusers_controller.rb
class ForgotusersController < ApplicationController
  # GET /forgotusers
  # GET /forgotusers.json
  def index
    @forgotusers = Forgotuser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @forgotusers }
    end
  end

  # GET /forgotusers/1
  # GET /forgotusers/1.json
  def show
    @forgotuser = Forgotuser.find(params[:id])
    Forgotuser.delete_all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @forgotuser }
      @answer1 = @forgotuser.securityAnswer

    if(@answer1 == session[:forgotAnswer])
          session[:showText] = 'true'
          @answer1 = nil
          redirect_to new_forgotuser_path(:mailid => session[:forgotId]) and return
    else
        @user = User.where(:emailId => session[:forgotId])[0]
        @user.update_attribute(:password, @forgotuser.newPassword)
        session[:showText] = 'false'
        #@forgotuser.destroy
        redirect_to login_path and return
    end
    
      end
  end

  # GET /forgotusers/new
  # GET /forgotusers/new.json
  def new
    @showText = session[:showText]
    @forgotuser = Forgotuser.new
    @user = User.where(:emailId => params[:mailid])[0]
    session[:forgotId] = @user.emailId
    @question = @user.securityQuestion
    @answer = @user.securityAnswer
    session[:forgotAnswer] = @answer
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @forgotuser }
    end
  end

  # GET /forgotusers/1/edit
  def edit
    @forgotuser = Forgotuser.find(params[:id])
  end

  # POST /forgotusers
  # POST /forgotusers.json
  def create
    @forgotuser = Forgotuser.new(params[:forgotuser])
    
    respond_to do |format|
      if @forgotuser.save
        format.html { redirect_to @forgotuser, notice: 'Forgotuser was successfully created.' }
        format.json { render json: @forgotuser, status: :created, location: @forgotuser }
      else
        format.html { render action: "new" }
        format.json { render json: @forgotuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /forgotusers/1
  # PUT /forgotusers/1.json
  def update
    @forgotuser = Forgotuser.find(params[:id])

    respond_to do |format|
      if @forgotuser.update_attributes(params[:forgotuser])
        format.html { redirect_to @forgotuser, notice: 'Forgotuser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @forgotuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forgotusers/1
  # DELETE /forgotusers/1.json
  def destroy
    @forgotuser = Forgotuser.find(params[:id])
    @forgotuser.destroy

    respond_to do |format|
      format.html { redirect_to forgotusers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/forgotusers_helper.rb
module ForgotusersHelper
end

app/views/forgotusers/_form.html.erb
<%= form_for(@forgotuser) do |f| %>
  <% if @forgotuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forgotuser.errors.count, "error") %> prohibited this forgotuser from being saved:</h2>

      <ul>
      <% @forgotuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= @showText %>
  
  <% if(@showText == 'false') %>
  <div class="field">
    <%= f.label :'securityQuestion : '%>   <%= @question %>
  </div>
  <div class="field">
    <%= f.label :securityAnswer %><br />
    <%= f.text_field :securityAnswer %>
  </div>
    <div class="field" style="visibility:hidden">
      <%= f.label :newPassword %><br />
      <%= f.text_field :newPassword %>
    </div>
  <%elsif(@showText == 'true')%>
  <div class="field" style="visibility:hidden">
    <%= f.label :securityQuestion %>   <%= @question %>
  </div>
  <div class="field" style="visibility:hidden">
    <%= f.label :securityAnswer %><br />
    <%= f.text_field :securityAnswer %>
  </div>
    <div class="field">
      <%= f.label :newPassword %><br />
      <%= f.text_field :newPassword %>
    </div>
  <%end%>
  <div class="actions">
    <%= f.submit :'Submit'%>
  </div>
<% end %>

app/views/forgotusers/edit.html.erb
<h1>Editing forgotuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @forgotuser %> |
<%= link_to 'Back', forgotusers_path %>

app/views/forgotusers/index.html.erb
<h1>Listing forgotusers</h1>

<table>
  <tr>
    <th>Securityquestion</th>
    <th>Securityanswer</th>
    <th>Newpassword</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @forgotusers.each do |forgotuser| %>
  <tr>
    <td><%= forgotuser.securityQuestion %></td>
    <td><%= forgotuser.securityAnswer %></td>
    <td><%= forgotuser.newPassword %></td>
    <td><%= link_to 'Show', forgotuser %></td>
    <td><%= link_to 'Edit', edit_forgotuser_path(forgotuser) %></td>
    <td><%= link_to 'Destroy', forgotuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Forgotuser', new_forgotuser_path %>

app/views/forgotusers/new.html.erb
<h1>New forgotuser</h1>

<%= render 'form' %>

<%= link_to 'Back', forgotusers_path %>

app/views/forgotusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Securityquestion:</b>
  <%= @forgotuser.securityQuestion %>
</p>

<p>
  <b>Securityanswer:</b>
  <%= @forgotuser.securityAnswer %>
</p>

<p>
  <b>Newpassword:</b>
  <%= @forgotuser.newPassword %>
</p>


<%= link_to 'Edit', edit_forgotuser_path(@forgotuser) %> |
<%= link_to 'Back', forgotusers_path %>